default:
  image: archlinux:latest

before_script:
  - pacman -Syu --needed --noconfirm asciidoc make

render:
  script:
    - make
  except:
    - schedules
    - tags

pages:
  tags:
    - secure
  script:
    - make
  artifacts:
    paths:
      - tu-bylaws.html
  only:
    - master
    - schedules
