default:
  image: archlinux:latest

before_script:
  - pacman -Syu --needed --noconfirm asciidoc make

render:
  script:
    - make
  except:
    - schedules
    - tags

pages:
  tags:
    - secure
  script:
    - make
    - mkdir public && mv tu-bylaws.html public/index.html
  artifacts:
    paths:
      - public
  only:
    - master
    - schedules
